# Generated by Django 4.0 on 2022-02-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[(1, '64'), (2, 'melee'), (3, 'brawl'), (4, 'for'), (5, 'ultimate')], max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('type', models.CharField(choices=[(0, 'super-heavy'), (1, 'heavy'), (2, 'heavy-middle'), (3, 'middle'), (4, 'middle-light'), (5, 'light'), (6, 'super-light')], max_length=15)),
                ('weight', models.IntegerField()),
                ('walk_spead', models.FloatField()),
                ('dash_speed', models.FloatField()),
                ('step_speed', models.FloatField()),
            ],
        ),
    ]
