# Generated by Django 4.0 on 2022-02-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_charactermodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermodel',
            name='category',
            field=models.CharField(choices=[('64', '64'), ('DX', 'melee'), ('X', 'brawl'), ('For', 'for'), ('SP', 'ultimate')], max_length=10),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='type',
            field=models.CharField(choices=[('super-heavy', 'super-heavy'), ('heavy', 'heavy'), ('heavy-middle', 'heavy-middle'), ('middle', 'middle'), ('middle-light', 'middle-light'), ('light', 'light'), ('super-light', 'super-light')], max_length=15),
        ),
    ]
